// Copyright (c) 2011 The LevelDB Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file. See the AUTHORS file for names of contributors.

#ifndef STORAGE_LEVELDB_INCLUDE_OPTIONS_H_
#define STORAGE_LEVELDB_INCLUDE_OPTIONS_H_

#include <cstddef>
#include <cstdint>

#include "leveldb/export.h"

namespace leveldb
{

class Cache;
class Comparator;
class Env;
class FilterPolicy;
class Logger;
class Snapshot;

// DB contents are stored in a set of blocks, each of which holds a
// sequence of key,value pairs.  Each block may be compressed before
// being stored in a file.  The following enum describes which
// compression method (if any) is used to compress a block.
// 数据库内容存储在一组块中，每个块包含一系列键值对。每个块在存储到文件之前可能会被压缩。以下枚举描述了使用哪种压缩方法（如果有的话）来压缩块。
enum class CompressionType : std::uint8_t
{
    // NOTE: do not change the values of existing entries, as these are
    // part of the persistent format on disk.
    kNoCompression = 0x0,
    kSnappyCompression = 0x1,
    kZstdCompression = 0x2,
};

// Options to control the behavior of a database (passed to DB::Open)
struct LEVELDB_EXPORT Options
{
        // Create an Options object with default values for all fields.
        Options();

        // -------------------
        // Parameters that affect behavior

        // Comparator used to define the order of keys in the table.
        // Default: a comparator that uses lexicographic byte-wise ordering
        //
        // REQUIRES: The client must ensure that the comparator supplied
        // here has the same name and orders keys *exactly* the same as the
        // comparator provided to previous open calls on the same DB.
        // 决定 user key 排序。默认是 byte-wise comparator。它是整个 LevelDB 有序性的根基。
        // 同一个 DB 后续打开时 comparator 的 name 和排序规则必须与之前完全一致。
        const Comparator* comparator; // default is BytewiseComparator

        // If true, the database will be created if it is missing.
        // 数据库目录不存在时是否创建。默认 false。
        bool create_if_missing = false;

        // If true, an error is raised if the database already exists.
        // 数据库已存在时是否报错。默认 false。
        bool error_if_exists = false;

        // If true, the implementation will do aggressive checking of the
        // data it is processing and will stop early if it detects any
        // errors.  This may have unforeseen ramifications: for example, a
        // corruption of one DB entry may cause a large number of entries to
        // become unreadable or for the entire DB to become unopenable.
        // 是否更激进地检查错误。开启后可能更早发现 corruption，但也可能导致更多数据不可读。
        bool paranoid_checks = false;

        // Use the specified object to interact with the environment,
        // e.g. to read/write files, schedule background work, etc.
        // Default: Env::Default()
        // 文件系统、线程调度、时间、锁等环境抽象。
        Env* env;

        // Any internal progress/error information generated by the db will
        // be written to info_log if it is non-null, or to a file stored
        // in the same directory as the DB contents if info_log is null.
        // LevelDB 内部日志输出位置。为空时会写到 DB 目录下的 LOG 文件。
        Logger* info_log = nullptr;

        // -------------------
        // Parameters that affect performance

        // Amount of data to build up in memory (backed by an unsorted log
        // on disk) before converting to a sorted on-disk file.
        //
        // Larger values increase performance, especially during bulk loads.
        // Up to two write buffers may be held in memory at the same time,
        // so you may wish to adjust this parameter to control memory usage.
        // Also, a larger write buffer will result in a longer recovery time
        // the next time the database is opened.
        // MemTable 写入多少数据后转换为磁盘 SSTable。默认 4MB。
        // 最多可能同时有两个 write buffer，所以它影响内存占用；值越大 bulk load 性能通常越好，但恢复时间也更长。
        size_t write_buffer_size = 4 * 1024 * 1024;

        // Number of open files that can be used by the DB.  You may need to
        // increase this if your database has a large working set (budget
        // one open file per 2MB of working set).
        // DB 可使用的打开文件数量。默认 1000。主要影响 TableCache 能缓存多少 SSTable 文件句柄。
        int max_open_files = 1000;

        // Control over blocks (user data is stored in a set of blocks, and
        // a block is the unit of reading from disk).

        // If non-null, use the specified cache for blocks.
        // If null, leveldb will automatically create and use an 8MB internal cache.
        // SSTable data block 的缓存。如果为空，LevelDB 会自动创建一个 8MB 内部 cache。
        Cache* block_cache = nullptr;

        // Approximate size of user data packed per block.  Note that the
        // block size specified here corresponds to uncompressed data.  The
        // actual size of the unit read from disk may be smaller if
        // compression is enabled.  This parameter can be changed dynamically.
        // SSTable 中每个 data block 近似容纳多少未压缩 user data。默认 4KB。它影响读放大、索引大小和压缩效率。
        size_t block_size = 4 * 1024;

        // Number of keys between restart points for delta encoding of keys.
        // This parameter can be changed dynamically.  Most clients should
        // leave this parameter alone.
        // BlockBuilder 前缀压缩中，每隔多少个 key 放一个 restart point。默认 16。
        int block_restart_interval = 16;

        // Leveldb will write up to this amount of bytes to a file before
        // switching to a new one.
        // Most clients should leave this parameter alone.  However if your
        // filesystem is more efficient with larger files, you could
        // consider increasing the value.  The downside will be longer
        // compactions and hence longer latency/performance hiccups.
        // Another reason to increase this parameter might be when you are
        // initially populating a large database.
        // 单个 SSTable 文件大小阈值。默认 2MB。文件过大，compaction
        // 延迟可能变长；文件过小，文件数量和元数据成本上升。增大它可能让 compaction 更长，从而带来更长延迟抖动。
        size_t max_file_size = 2 * 1024 * 1024;

        // Compress blocks using the specified compression algorithm.  This
        // parameter can be changed dynamically.
        //
        // Default: kSnappyCompression, which gives lightweight but fast
        // compression.
        //
        // Typical speeds of kSnappyCompression on an Intel(R) Core(TM)2 2.4GHz:
        //    ~200-500MB/s compression
        //    ~400-800MB/s decompression
        // Note that these speeds are significantly faster than most
        // persistent storage speeds, and therefore it is typically never
        // worth switching to kNoCompression.  Even if the input data is
        // incompressible, the kSnappyCompression implementation will
        // efficiently detect that and will switch to uncompressed mode.
        // block 压缩算法。默认 Snappy。当前源码还包含 Zstd 选项。
        CompressionType compression = CompressionType::kSnappyCompression;

        // Compression level for zstd.
        // Currently only the range [-5,22] is supported. Default is 1.
        int zstd_compression_level = 1;

        // EXPERIMENTAL: If true, append to existing MANIFEST and log files
        // when a database is opened.  This can significantly speed up open.
        //
        // Default: currently false, but may become true later.
        bool reuse_logs = false;

        // If non-null, use the specified filter policy to reduce disk reads.
        // Many applications will benefit from passing the result of
        // NewBloomFilterPolicy() here.
        // 过滤策略，典型是 Bloom Filter。它用于减少无效磁盘读取。为空则不开启 filter。
        const FilterPolicy* filter_policy = nullptr;
};

// Options that control read operations
struct LEVELDB_EXPORT ReadOptions
{
        // If true, all data read from underlying storage will be
        // verified against corresponding checksums.
        // 读取底层存储数据时是否校验 checksum。
        bool verify_checksums = false;

        // Should the data read for this iteration be cached in memory?
        // Callers may wish to set this field to false for bulk scans.
        // 这次读取是否把读到的数据放入 block cache。大范围扫描时可以设为 false，避免污染缓存。
        bool fill_cache = true;

        // If "snapshot" is non-null, read as of the supplied snapshot
        // (which must belong to the DB that is being read and which must
        // not have been released).  If "snapshot" is null, use an implicit
        // snapshot of the state at the beginning of this read operation.
        // 指定读视图。不为空时读指定 snapshot；为空时使用本次读开始时的隐式 snapshot。
        const Snapshot* snapshot = nullptr;
};

// Options that control write operations
struct LEVELDB_EXPORT WriteOptions
{
        WriteOptions() = default;

        // If true, the write will be flushed from the operating system
        // buffer cache (by calling WritableFile::Sync()) before the write
        // is considered complete.  If this flag is true, writes will be
        // slower.
        //
        // If this flag is false, and the machine crashes, some recent
        // writes may be lost.  Note that if it is just the process that
        // crashes (i.e., the machine does not reboot), no writes will be
        // lost even if sync==false.
        //
        // In other words, a DB write with sync==false has similar
        // crash semantics as the "write()" system call.  A DB write
        // with sync==true has similar crash semantics to a "write()"
        // system call followed by "fsync()".
        // 写入是否在返回前调用 WritableFile::Sync()。源码注释把 sync=false 类比成普通 write()，把 sync=true 类比成
        // write() 后跟 fsync()；sync=true 更慢，但机器崩溃时更安全。
        // sync=false：LevelDB 会写 WAL，但可能只是写到了操作系统 page cache。进程崩溃但机器没重启时，OS cache
        // 还在，通常不丢；机器断电或系统崩溃时，最近写入可能丢。
        // sync=true：LevelDB 写 WAL 后还调用 Sync()，让操作系统尽量把数据刷到持久化设备。它更慢，但崩溃恢复语义更强。
        bool sync = false;
};

} // namespace leveldb

#endif // STORAGE_LEVELDB_INCLUDE_OPTIONS_H_
